// Catalogue : icônes, polices, palettes, blocs. Source unique de vérité pour
// le moteur, le studio, le normaliseur et le prompt de l'IA.

// Icônes autorisées (noms Lucide en kebab-case)
export const ICONS = [
  'home', 'search', 'shopping-bag', 'shopping-cart', 'heart', 'user', 'users', 'bell', 'settings', 'menu', 'x', 'check',
  'chevron-right', 'chevron-left', 'arrow-right', 'arrow-left', 'arrow-up-right', 'arrow-down-left', 'plus', 'minus',
  'star', 'map-pin', 'map', 'navigation', 'clock', 'calendar', 'calendar-days', 'phone', 'message-circle', 'send', 'mail',
  'lock', 'shield-check', 'credit-card', 'wallet', 'banknote', 'coins', 'piggy-bank', 'receipt', 'trending-up', 'trending-down',
  'chart-bar', 'chart-line', 'pie-chart', 'activity', 'zap', 'flame', 'sparkles', 'gift', 'tag', 'percent', 'truck', 'bike',
  'car', 'car-taxi-front', 'bus', 'plane', 'package', 'package-check', 'store', 'utensils', 'chef-hat', 'pizza', 'coffee',
  'cup-soda', 'soup', 'sandwich', 'salad', 'drumstick', 'croissant', 'ice-cream', 'cake', 'apple', 'carrot', 'fish',
  'scissors', 'brush', 'palette', 'shirt', 'gem', 'crown', 'dumbbell', 'heart-pulse', 'stethoscope', 'pill', 'hospital',
  'syringe', 'baby', 'graduation-cap', 'book-open', 'school', 'lightbulb', 'brain', 'music', 'headphones', 'film', 'video',
  'camera', 'image', 'mic', 'play', 'pause', 'smartphone', 'laptop', 'globe', 'leaf', 'sprout', 'sun', 'cloud-sun',
  'cloud-rain', 'droplets', 'wind', 'thermometer', 'tractor', 'wheat', 'building', 'building-2', 'hotel', 'bed', 'bath',
  'key', 'sofa', 'wrench', 'hammer', 'paintbrush', 'spray-can', 'ticket', 'party-popper', 'trophy', 'medal', 'target',
  'flag', 'filter', 'sliders-horizontal', 'layout-grid', 'list', 'share-2', 'download', 'upload', 'copy', 'pencil', 'trash-2',
  'eye', 'log-out', 'info', 'circle-alert', 'circle-help', 'qr-code', 'scan-line', 'fingerprint', 'smile', 'thumbs-up',
  'bookmark', 'repeat', 'refresh-cw', 'timer', 'hourglass', 'award', 'badge-check', 'handshake', 'briefcase', 'newspaper',
  'megaphone', 'rocket', 'locate', 'route', 'warehouse', 'boxes', 'recycle', 'moon', 'languages', 'dog', 'cat', 'flower-2',
  'tree-pine', 'mountain', 'waves', 'umbrella', 'tent', 'ship', 'train-front', 'fuel', 'circle-dollar-sign', 'hand-coins',
  'landmark', 'scale', 'file-text', 'clipboard-list', 'clipboard-check', 'calculator', 'map-pinned', 'luggage', 'headset',
  'tv', 'gamepad-2', 'puzzle', 'wand-sparkles', 'glasses', 'watch', 'footprints', 'shopping-basket', 'id-card', 'shield',
  'wifi', 'sun-medium', 'box', 'house', 'hand-heart', 'circle-check', 'circle-play', 'layers', 'book', 'notebook-pen',
];

// Mots courants -> icône
export const ICON_ALIASES = {
  accueil: 'home', maison: 'house', recherche: 'search', rechercher: 'search', panier: 'shopping-bag', cart: 'shopping-cart', basket: 'shopping-basket',
  bag: 'shopping-bag', favoris: 'heart', favorite: 'heart', favorites: 'heart', like: 'heart', profil: 'user', profile: 'user', account: 'user', compte: 'user',
  notifications: 'bell', notification: 'bell', parametres: 'settings', reglages: 'settings', gear: 'settings', close: 'x', delete: 'trash-2', trash: 'trash-2',
  edit: 'pencil', location: 'map-pin', adresse: 'map-pin', address: 'map-pin', pin: 'map-pin', time: 'clock', heure: 'clock', date: 'calendar', rdv: 'calendar-days',
  appointment: 'calendar-days', booking: 'calendar-days', reservation: 'calendar-days', call: 'phone', appel: 'phone', chat: 'message-circle', message: 'message-circle',
  messages: 'message-circle', whatsapp: 'message-circle', email: 'mail', security: 'shield-check', securite: 'shield-check', card: 'credit-card', carte: 'credit-card',
  payment: 'wallet', paiement: 'wallet', money: 'banknote', argent: 'banknote', cash: 'banknote', savings: 'piggy-bank', epargne: 'piggy-bank', tontine: 'hand-coins',
  invoice: 'receipt', facture: 'receipt', stats: 'chart-bar', statistics: 'chart-bar', chart: 'chart-line', analytics: 'chart-line', promo: 'percent', discount: 'percent',
  offer: 'tag', offre: 'tag', delivery: 'truck', livraison: 'truck', moto: 'bike', scooter: 'bike', taxi: 'car-taxi-front', vtc: 'car', order: 'package',
  commande: 'package', commandes: 'package', orders: 'package', shop: 'store', boutique: 'store', food: 'utensils', restaurant: 'utensils', cuisine: 'chef-hat',
  drink: 'cup-soda', boisson: 'cup-soda', juice: 'cup-soda', jus: 'cup-soda', hair: 'scissors', coiffure: 'scissors', beauty: 'sparkles', beaute: 'sparkles',
  makeup: 'brush', fashion: 'shirt', mode: 'shirt', clothes: 'shirt', luxury: 'gem', premium: 'crown', vip: 'crown', gym: 'dumbbell', fitness: 'dumbbell',
  sport: 'trophy', health: 'heart-pulse', sante: 'heart-pulse', doctor: 'stethoscope', medecin: 'stethoscope', pharmacy: 'pill', pharmacie: 'pill',
  education: 'graduation-cap', cours: 'book-open', course: 'book-open', lesson: 'book-open', learn: 'lightbulb', music: 'music', musique: 'music', video: 'circle-play',
  photo: 'camera', phone_: 'smartphone', web: 'globe', langue: 'languages', language: 'languages', nature: 'leaf', plant: 'sprout', weather: 'cloud-sun', meteo: 'cloud-sun',
  rain: 'cloud-rain', pluie: 'cloud-rain', water: 'droplets', eau: 'droplets', farm: 'tractor', agriculture: 'wheat', building_: 'building-2', immobilier: 'building-2',
  hotel_: 'hotel', room: 'bed', chambre: 'bed', repair: 'wrench', reparation: 'wrench', cleaning: 'spray-can', menage: 'spray-can', event: 'party-popper',
  evenement: 'party-popper', ticket_: 'ticket', billet: 'ticket', reward: 'award', fidelite: 'award', loyalty: 'award', goal: 'target', objectif: 'target',
  share: 'share-2', partager: 'share-2', help: 'circle-help', aide: 'circle-help', support: 'headset', logout: 'log-out', deconnexion: 'log-out', qr: 'qr-code',
  scan: 'scan-line', verified: 'badge-check', verifie: 'badge-check', partner: 'handshake', work: 'briefcase', travail: 'briefcase', news: 'newspaper',
  actualites: 'newspaper', launch: 'rocket', history: 'clock', historique: 'clock', wallet_: 'wallet', transfer: 'send', envoyer: 'send', receive: 'arrow-down-left',
  recevoir: 'arrow-down-left', dark: 'moon', add: 'plus', ajouter: 'plus', success: 'circle-check', play_: 'play', gift_: 'gift', cadeau: 'gift', bank: 'landmark',
  banque: 'landmark', document: 'file-text', documents: 'file-text', quiz: 'clipboard-check', travel: 'luggage', voyage: 'luggage', game: 'gamepad-2', jeu: 'gamepad-2',
  id: 'id-card', identite: 'id-card', couture: 'scissors', tailleur: 'scissors', grocery: 'shopping-basket', courses: 'shopping-basket', marche: 'shopping-basket',
};

// Polices Google autorisées
export const FONTS = {
  'Plus Jakarta Sans': 'sans', Inter: 'sans', Manrope: 'sans', 'DM Sans': 'sans', Outfit: 'sans', Poppins: 'sans', Sora: 'sans',
  'Space Grotesk': 'sans', Urbanist: 'sans', Figtree: 'sans', Onest: 'sans', 'Bricolage Grotesque': 'sans', Geist: 'sans', Lexend: 'sans',
  Nunito: 'sans', Rubik: 'sans', Syne: 'sans', Unbounded: 'sans', Montserrat: 'sans', 'Work Sans': 'sans',
  Fraunces: 'serif', 'Playfair Display': 'serif', 'DM Serif Display': 'serif', 'Instrument Serif': 'serif', 'Cormorant Garamond': 'serif',
  Lora: 'serif', 'Young Serif': 'serif', Gloock: 'serif',
};

export const FONT_PAIRS = [
  { id: 'moderne', label: 'Moderne', heading: 'Plus Jakarta Sans', body: 'Plus Jakarta Sans' },
  { id: 'elegant', label: 'Élégant', heading: 'Fraunces', body: 'Manrope' },
  { id: 'luxe', label: 'Luxe', heading: 'Playfair Display', body: 'Inter' },
  { id: 'tech', label: 'Tech', heading: 'Space Grotesk', body: 'Inter' },
  { id: 'rond', label: 'Rond', heading: 'Outfit', body: 'Outfit' },
  { id: 'editorial', label: 'Éditorial', heading: 'Instrument Serif', body: 'Geist' },
  { id: 'audacieux', label: 'Audacieux', heading: 'Bricolage Grotesque', body: 'DM Sans' },
  { id: 'futuriste', label: 'Futuriste', heading: 'Unbounded', body: 'Sora' },
  { id: 'doux', label: 'Doux', heading: 'Nunito', body: 'Nunito' },
  { id: 'classique', label: 'Classique', heading: 'DM Serif Display', body: 'DM Sans' },
];

export const PALETTES = [
  { id: 'sunset', label: 'Coucher de soleil', mode: 'light', primary: '#FF5A36', accent: '#FFB23F' },
  { id: 'bissap', label: 'Bissap', mode: 'light', primary: '#B0164E', accent: '#F4A259' },
  { id: 'baobab', label: 'Baobab', mode: 'light', primary: '#1F7A5A', accent: '#F2B544' },
  { id: 'ocean', label: 'Atlantique', mode: 'light', primary: '#0A6CFF', accent: '#00C2A8' },
  { id: 'nuit', label: 'Nuit de Dakar', mode: 'dark', primary: '#8B6CFF', accent: '#FF6AD5' },
  { id: 'sable', label: 'Sable', mode: 'light', primary: '#C2703D', accent: '#2F4858', background: '#FBF7F1' },
  { id: 'menthe', label: 'Menthe', mode: 'light', primary: '#0FB57E', accent: '#0B3D2E' },
  { id: 'or', label: 'Or & Noir', mode: 'dark', primary: '#E3B341', accent: '#F5E6C8' },
  { id: 'corail', label: 'Corail', mode: 'light', primary: '#FF6B6B', accent: '#2EC4B6' },
  { id: 'indigo', label: 'Indigo', mode: 'light', primary: '#4F46E5', accent: '#F59E0B' },
  { id: 'lagon', label: 'Lagon', mode: 'dark', primary: '#22D3EE', accent: '#A3E635' },
  { id: 'kora', label: 'Kora', mode: 'light', primary: '#E76F51', accent: '#264653' },
];

export const STYLES = ['soft', 'glass', 'bold', 'minimal', 'editorial'];

// Moyens de paiement
export const PAY_METHODS = {
  wave: { label: 'Wave', short: 'W', color: '#1DC8F2', ink: '#063a4a', hint: 'Paiement instantané' },
  orange_money: { label: 'Orange Money', short: 'OM', color: '#FF7900', ink: '#ffffff', hint: 'Code secret sur ton téléphone' },
  free_money: { label: 'Mixx by Yas', short: 'Mx', color: '#E4003B', ink: '#ffffff', hint: 'Ex-Free Money' },
  card: { label: 'Carte bancaire', short: 'CB', color: '#1F2937', ink: '#ffffff', hint: 'Visa, Mastercard' },
  cash: { label: 'À la livraison', short: '₣', color: '#16A34A', ink: '#ffffff', hint: 'Espèces à la réception' },
};

// Catalogue des blocs (libellés FR pour le studio)
export const BLOCKS = {
  hero: { label: 'Bannière vidéo', icon: 'film', group: 'Médias' },
  video: { label: 'Vidéo', icon: 'circle-play', group: 'Médias' },
  gallery: { label: 'Galerie', icon: 'image', group: 'Médias' },
  stories: { label: 'Stories', icon: 'circle-play', group: 'Médias' },
  illustration: { label: 'Illustration animée', icon: 'wand-sparkles', group: 'Médias' },
  search: { label: 'Recherche', icon: 'search', group: 'Navigation' },
  chips: { label: 'Filtres', icon: 'sliders-horizontal', group: 'Navigation' },
  segmented: { label: 'Onglets', icon: 'layout-grid', group: 'Navigation' },
  categories: { label: 'Catégories', icon: 'layout-grid', group: 'Navigation' },
  actions: { label: 'Actions rapides', icon: 'zap', group: 'Navigation' },
  carousel: { label: 'Carrousel', icon: 'layers', group: 'Contenu' },
  products: { label: 'Grille produits', icon: 'shopping-bag', group: 'Commerce' },
  list: { label: 'Liste', icon: 'list', group: 'Contenu' },
  feed: { label: 'Fil social', icon: 'newspaper', group: 'Contenu' },
  promo: { label: 'Promo', icon: 'percent', group: 'Contenu' },
  text: { label: 'Texte', icon: 'file-text', group: 'Contenu' },
  features: { label: 'Atouts', icon: 'sparkles', group: 'Contenu' },
  notice: { label: 'Message', icon: 'info', group: 'Contenu' },
  faq: { label: 'FAQ', icon: 'circle-help', group: 'Contenu' },
  reviews: { label: 'Avis', icon: 'star', group: 'Contenu' },
  button: { label: 'Bouton', icon: 'arrow-right', group: 'Contenu' },
  detail: { label: 'Fiche détail', icon: 'tag', group: 'Commerce' },
  cart: { label: 'Panier', icon: 'shopping-cart', group: 'Commerce' },
  checkout: { label: 'Paiement Mobile Money', icon: 'wallet', group: 'Commerce' },
  success: { label: 'Confirmation', icon: 'circle-check', group: 'Commerce' },
  plans: { label: 'Offres / abonnements', icon: 'crown', group: 'Commerce' },
  booking: { label: 'Réservation', icon: 'calendar-days', group: 'Services' },
  tracking: { label: 'Suivi en direct', icon: 'route', group: 'Services' },
  map: { label: 'Carte', icon: 'map', group: 'Services' },
  timeline: { label: 'Étapes', icon: 'clipboard-list', group: 'Services' },
  ticket: { label: 'Billet / reçu', icon: 'ticket', group: 'Services' },
  countdown: { label: 'Compte à rebours', icon: 'timer', group: 'Services' },
  contact: { label: 'Contact', icon: 'phone', group: 'Services' },
  balance: { label: 'Solde / carte', icon: 'wallet', group: 'Finance' },
  stats: { label: 'Chiffres clés', icon: 'activity', group: 'Finance' },
  chart: { label: 'Graphique', icon: 'chart-line', group: 'Finance' },
  progress: { label: 'Objectif', icon: 'target', group: 'Finance' },
  form: { label: 'Formulaire', icon: 'clipboard-list', group: 'Compte' },
  auth: { label: 'Connexion', icon: 'lock', group: 'Compte' },
  profile: { label: 'Profil', icon: 'user', group: 'Compte' },
  settings: { label: 'Menu / réglages', icon: 'settings', group: 'Compte' },
  chat: { label: 'Messagerie', icon: 'message-circle', group: 'Compte' },
  onboarding: { label: 'Onboarding', icon: 'rocket', group: 'Compte' },
  spacer: { label: 'Espace', icon: 'minus', group: 'Contenu' },
  editorial: { label: 'Éditorial', icon: 'newspaper', group: 'Signature' },
  showcase: { label: 'Lookbook', icon: 'layers', group: 'Signature' },
  bento: { label: 'Mosaïque bento', icon: 'layout-grid', group: 'Signature' },
  marquee: { label: 'Bandeau défilant', icon: 'megaphone', group: 'Signature' },
  team: { label: 'Équipe', icon: 'users', group: 'Signature' },
  quote: { label: 'Citation', icon: 'message-circle', group: 'Signature' },
};

export const BLOCK_TYPES = Object.keys(BLOCKS);

// Alias fréquents renvoyés par les IA -> type canonique
export const BLOCK_ALIASES = {
  herovideo: 'hero', banner: 'promo', videohero: 'hero', header: 'hero', cover: 'hero', jumbotron: 'hero', splash: 'hero',
  productgrid: 'products', productlist: 'products', grid: 'products', catalog: 'products', catalogue: 'products', menugrid: 'products', menuitems: 'products', dishes: 'products', items: 'products', shop: 'products',
  transactions: 'list', transactionlist: 'list', orders: 'list', orderlist: 'list', listview: 'list', rows: 'list', menulist: 'list', notifications: 'list',
  slides: 'onboarding', intro: 'onboarding', walkthrough: 'onboarding', welcome: 'onboarding',
  login: 'auth', signup: 'auth', register: 'auth', otp: 'auth', signin: 'auth', connexion: 'auth',
  account: 'profile', user: 'profile', usercard: 'profile',
  menu: 'settings', options: 'settings', preferences: 'settings', settingslist: 'settings',
  messages: 'chat', conversation: 'chat', messaging: 'chat', support: 'chat', assistant: 'chat',
  pricing: 'plans', subscription: 'plans', subscriptions: 'plans', offers: 'plans', tiers: 'plans',
  testimonials: 'reviews', ratings: 'reviews', review: 'reviews',
  shortcuts: 'actions', quickactions: 'actions', actiongrid: 'actions', services: 'categories', iconsgrid: 'categories',
  paragraph: 'text', heading: 'text', title: 'text', richtext: 'text', description: 'text', section: 'text',
  cta: 'button', buttons: 'button', ctabutton: 'button',
  alert: 'notice', info: 'notice', callout: 'notice', banneralert: 'notice', tip: 'notice',
  goal: 'progress', progressbar: 'progress', progressring: 'progress',
  timer: 'countdown', pass: 'ticket', boardingpass: 'ticket', receipt: 'ticket', qrcode: 'ticket',
  location: 'map', mapview: 'map', ordertracking: 'tracking', deliverytracking: 'tracking', livetracking: 'tracking', ride: 'tracking',
  benefits: 'features', featurelist: 'features', usp: 'features', accordion: 'faq', questions: 'faq',
  contactcard: 'contact', callus: 'contact', emptystate: 'illustration', empty: 'illustration', animation: 'illustration', lottie: 'illustration',
  segment: 'segmented', tabs: 'segmented', filters: 'chips', tags: 'chips', filterchips: 'chips', categorychips: 'chips',
  wallet: 'balance', balancecard: 'balance', walletcard: 'balance', creditcard: 'balance', account_balance: 'balance',
  story: 'stories', posts: 'feed', social: 'feed', socialfeed: 'feed', timelinefeed: 'feed',
  photos: 'gallery', images: 'gallery', player: 'video', videoplayer: 'video', videocard: 'video',
  productdetail: 'detail', itemdetail: 'detail', servicedetail: 'detail', productdetails: 'detail', details: 'detail',
  basket: 'cart', panier: 'cart', shoppingcart: 'cart',
  payment: 'checkout', paymentmethods: 'checkout', mobilemoney: 'checkout', pay: 'checkout', paiement: 'checkout',
  confirmation: 'success', thankyou: 'success', done: 'success', orderconfirmation: 'success',
  steps: 'timeline', orderstatus: 'timeline', stepper: 'timeline', history: 'timeline',
  calendar: 'booking', appointment: 'booking', reservation: 'booking', timeslots: 'booking', slots: 'booking', datepicker: 'booking',
  inputs: 'form', contactform: 'form', kpi: 'stats', kpis: 'stats', metrics: 'stats', counters: 'stats',
  graph: 'chart', linechart: 'chart', barchart: 'chart', areachart: 'chart', bar: 'chart', area: 'chart', sparkline: 'chart',
  carrousel: 'carousel', slider: 'carousel', horizontallist: 'carousel', cards: 'carousel',
  divider: 'spacer', separator: 'spacer', gap: 'spacer',
  story_text: 'editorial', statement: 'editorial', manifesto: 'editorial', intro_text: 'editorial', about: 'editorial', storytelling: 'editorial',
  lookbook: 'showcase', collection: 'showcase', spotlight: 'showcase', featured: 'showcase', highlights: 'showcase',
  mosaic: 'bento', bentogrid: 'bento', tiles: 'bento', overview: 'bento',
  ticker: 'marquee', scrollingtext: 'marquee', band: 'marquee', tickertape: 'marquee',
  staff: 'team', experts: 'team', members: 'team', people: 'team', crew: 'team', doctors: 'team', stylists: 'team',
  testimonial: 'quote', citation: 'quote', blockquote: 'quote', pullquote: 'quote',
};
