// Blocs et écrans prêts à l'emploi pour l'éditeur (contenus d'exemple en français).
export const BLOCK_PRESETS = {
  hero: () => ({ type: 'hero', title: 'Ton titre accrocheur', subtitle: 'Une phrase qui donne envie en quelques mots.', media: { video: 'city dusk aerial skyline' }, height: 'medium', buttons: [{ label: 'Découvrir' }] }),
  video: () => ({ type: 'video', title: 'Dans les coulisses', subtitle: 'Présente ton savoir-faire en vidéo.', media: { video: 'business team meeting office' }, duration: '0:45' }),
  gallery: () => ({ type: 'gallery', title: 'Galerie', layout: 'masonry', images: ['dakar city street', 'senegal boats beach', 'african food feast', 'fashion african woman'] }),
  stories: () => ({ type: 'stories', items: [{ name: 'Nouveautés', image: 'fashion african woman' }, { name: 'Promo', image: 'shopping bags women' }, { name: 'Coulisses', image: 'business team african' }] }),
  illustration: () => ({ type: 'illustration', name: 'success', title: 'Tout est prêt', text: 'Explique ici ce qui se passe.' }),
  search: () => ({ type: 'search', placeholder: 'Rechercher…' }),
  chips: () => ({ type: 'chips', items: ['Tout', 'Populaire', 'Nouveau', 'Promo'] }),
  segmented: () => ({ type: 'segmented', items: ['En cours', 'Terminées'] }),
  categories: () => ({ type: 'categories', title: 'Catégories', items: [{ label: 'Repas', icon: 'utensils' }, { label: 'Courses', icon: 'shopping-basket' }, { label: 'Colis', icon: 'package' }, { label: 'Taxi', icon: 'car' }] }),
  actions: () => ({ type: 'actions', items: [{ label: 'Envoyer', icon: 'send' }, { label: 'Recevoir', icon: 'arrow-down-left' }, { label: 'Payer', icon: 'qr-code' }, { label: 'Plus', icon: 'layout-grid' }] }),
  carousel: () => ({ type: 'carousel', title: 'À la une', style: 'card', items: [{ title: 'Élément 1', subtitle: 'Description courte', image: 'african food plate', price: 2500, rating: 4.8 }, { title: 'Élément 2', subtitle: 'Description courte', image: 'fashion african dress', price: 15000, rating: 4.7 }, { title: 'Élément 3', subtitle: 'Description courte', image: 'handbag leather', price: 12000, rating: 4.9 }] }),
  products: () => ({ type: 'products', title: 'Produits', items: [{ title: 'Produit 1', subtitle: 'Détail', price: 5000, image: 'product sneakers' }, { title: 'Produit 2', subtitle: 'Détail', price: 7500, image: 'product handbag' }, { title: 'Produit 3', subtitle: 'Détail', price: 3000, image: 'product cosmetics' }, { title: 'Produit 4', subtitle: 'Détail', price: 12000, image: 'product watch' }] }),
  list: () => ({ type: 'list', title: 'Liste', items: [{ title: 'Premier élément', subtitle: 'Sous-titre', icon: 'star' }, { title: 'Deuxième élément', subtitle: 'Sous-titre', icon: 'heart' }, { title: 'Troisième élément', subtitle: 'Sous-titre', icon: 'zap' }] }),
  feed: () => ({ type: 'feed', items: [{ author: 'Awa Diop', text: 'Première publication de la communauté 🎉', media: { image: 'people friends african' }, time: 'il y a 1 h' }] }),
  promo: () => ({ type: 'promo', eyebrow: 'Offre limitée', title: '-20 % cette semaine', subtitle: 'Profite de nos meilleurs prix.', code: 'TERANGA20', tone: 'gradient', cta: { label: 'J\'en profite' } }),
  text: () => ({ type: 'text', title: 'Un titre', text: 'Un paragraphe qui explique ton service simplement.' }),
  features: () => ({ type: 'features', title: 'Pourquoi nous ?', items: [{ icon: 'zap', title: 'Rapide', text: 'Service en moins d\'une heure' }, { icon: 'shield-check', title: 'Sécurisé', text: 'Paiement protégé' }] }),
  notice: () => ({ type: 'notice', icon: 'info', title: 'Bon à savoir', text: 'Un message important pour tes clients.', tone: 'info' }),
  faq: () => ({ type: 'faq', items: [{ q: 'Comment payer ?', a: 'Par Wave, Orange Money, Mixx by Yas ou carte bancaire.' }, { q: 'Livrez-vous partout ?', a: 'Oui, partout à Dakar en moins de 24 h.' }] }),
  reviews: () => ({ type: 'reviews', rating: 4.8, count: 120, items: [{ author: 'Fatou Sow', rating: 5, text: 'Excellent service, je recommande !', date: 'hier' }] }),
  button: () => ({ type: 'button', label: 'Continuer' }),
  spacer: () => ({ type: 'spacer', size: 24, line: true }),
  detail: () => ({ type: 'detail', title: 'Nom du produit', subtitle: 'Vendeur', price: 10000, media: { image: 'product photography' }, description: 'Décris ton produit ou service ici.', options: [{ name: 'Taille', values: ['S', 'M', 'L'] }] }),
  cart: () => ({ type: 'cart', fee: 1000, feeLabel: 'Livraison' }),
  checkout: () => ({ type: 'checkout', methods: ['wave', 'orange_money', 'free_money', 'card', 'cash'] }),
  success: () => ({ type: 'success', title: 'C\'est confirmé !', subtitle: 'Merci pour ta confiance.' }),
  plans: () => ({ type: 'plans', title: 'Nos offres', items: [{ name: 'Essentiel', price: 5000, period: '/mois', features: ['Accès de base'] }, { name: 'Premium', price: 15000, period: '/mois', highlight: true, features: ['Tout inclus', 'Support prioritaire'] }] }),
  booking: () => ({ type: 'booking', title: 'Choisis ton créneau' }),
  tracking: () => ({ type: 'tracking', title: 'Ta commande arrive', eta: '12 min', courier: { name: 'Moussa Ndiaye', vehicle: 'Moto · DK 2451 AB' } }),
  map: () => ({ type: 'map', title: 'Nous trouver', pins: [{ label: 'Boutique' }], caption: 'Plateau, Dakar' }),
  timeline: () => ({ type: 'timeline', title: 'Étapes', items: [{ title: 'Commande reçue', time: '10:02', done: true }, { title: 'En préparation', time: '10:10', done: true }, { title: 'En route', done: false }] }),
  ticket: () => ({ type: 'ticket', title: 'Ton billet', subtitle: 'Entrée standard', date: 'Sam. 18 oct.', time: '21:00', place: 'Dakar' }),
  countdown: () => ({ type: 'countdown', title: 'Vente flash', label: 'Se termine dans', hours: 6 }),
  contact: () => ({ type: 'contact', phone: '+221 77 000 00 00', address: 'Plateau, Dakar', hours: 'Lun – Sam · 9h – 19h' }),
  balance: () => ({ type: 'balance', label: 'Solde disponible', amount: 125000, actions: [{ label: 'Envoyer', icon: 'send' }, { label: 'Recevoir', icon: 'arrow-down-left' }] }),
  stats: () => ({ type: 'stats', items: [{ label: 'Ventes', value: 128, icon: 'shopping-bag', trend: '+12%' }, { label: 'Clients', value: 86, icon: 'users', trend: '+5%' }] }),
  chart: () => ({ type: 'chart', title: 'Chiffre d\'affaires', value: '1 250 000 F', change: '+18 %', period: '7 jours', series: [12, 18, 15, 22, 28, 24, 34], labels: ['L', 'M', 'M', 'J', 'V', 'S', 'D'] }),
  progress: () => ({ type: 'progress', title: 'Objectif', value: 64, max: 100, unit: '%', label: 'Continue comme ça !' }),
  form: () => ({ type: 'form', title: 'Contacte-nous', fields: [{ label: 'Nom complet', type: 'text' }, { label: 'Téléphone', type: 'phone' }, { label: 'Message', type: 'textarea' }], submit: { label: 'Envoyer' } }),
  auth: () => ({ type: 'auth', title: 'Bienvenue 👋', subtitle: 'Connecte-toi avec ton numéro' }),
  profile: () => ({ type: 'profile', name: 'Awa Diop', subtitle: '+221 77 123 45 67', stats: [{ label: 'Commandes', value: '12' }, { label: 'Points', value: '340' }] }),
  settings: () => ({ type: 'settings', groups: [{ title: 'Compte', items: [{ label: 'Informations', icon: 'user' }, { label: 'Notifications', icon: 'bell', toggle: true }, { label: 'Se déconnecter', icon: 'log-out', danger: true }] }] }),
  chat: () => ({ type: 'chat', contact: { name: 'Service client', status: 'En ligne' }, quick: ['Bonjour !', 'J\'ai une question'] }),
  onboarding: () => ({ type: 'onboarding', slides: [{ title: 'Bienvenue', text: 'Présente ton app en une phrase.', media: { video: 'city dusk aerial' } }, { title: 'Simple et rapide', text: 'Deuxième argument clé.', illustration: 'success' }] }),
  editorial: () => ({ type: 'editorial', eyebrow: 'Notre histoire', title: 'Fait à Dakar, *avec passion*', text: 'Raconte en deux phrases ce qui rend ta maison unique : ton savoir-faire, tes produits, ton accueil.', author: { name: 'Awa Diop', role: 'Fondatrice' }, tone: 'plain' }),
  showcase: () => ({ type: 'showcase', eyebrow: 'Sélection', title: 'Nos *incontournables*', items: [{ title: 'Signature', subtitle: 'Le best-seller de la maison', image: 'african food plate', price: 3500, rating: 4.9 }, { title: 'Nouveauté', subtitle: 'À découvrir cette semaine', image: 'fashion african dress', price: 15000 }, { title: 'Coup de cœur', subtitle: 'Choisi par nos clients', image: 'handbag leather', price: 12000 }] }),
  bento: () => ({ type: 'bento', eyebrow: 'En bref', title: 'Pourquoi *nous*', items: [{ kind: 'image', title: 'Notre atelier', image: 'workshop craftsman africa', tall: true }, { kind: 'stat', title: 'Clients satisfaits', value: 2400, suffix: '+', icon: 'smile' }, { kind: 'feature', title: 'Livraison 24 h', text: 'Partout à Dakar', icon: 'truck' }, { kind: 'text', title: 'Qualité *garantie*', text: 'Satisfait ou échangé.', span: 2 }] }),
  marquee: () => ({ type: 'marquee', items: ['Fait à Dakar', 'Livraison rapide', 'Paiement Wave', 'Qualité garantie'], tone: 'primary' }),
  team: () => ({ type: 'team', eyebrow: 'L\'équipe', title: 'Les *experts*', items: [{ name: 'Awa Diop', role: 'Fondatrice', rating: 4.9 }, { name: 'Moussa Ndiaye', role: 'Expert', rating: 4.8 }, { name: 'Fatou Sow', role: 'Conseillère', rating: 5 }] }),
  quote: () => ({ type: 'quote', text: 'Un service *impeccable*, je recommande à toute ma famille.', author: 'Aminata Ba', role: 'Cliente depuis 2023', rating: 5 }),
};

export const SCREEN_PRESETS = [
  { id: 'vide', label: 'Écran vide', icon: 'file-text', blocks: () => [BLOCK_PRESETS.text()], header: 'compact' },
  { id: 'accueil', label: 'Accueil', icon: 'home', blocks: () => [BLOCK_PRESETS.hero(), BLOCK_PRESETS.categories(), BLOCK_PRESETS.carousel()], header: 'large' },
  { id: 'catalogue', label: 'Catalogue', icon: 'shopping-bag', blocks: () => [BLOCK_PRESETS.search(), BLOCK_PRESETS.chips(), BLOCK_PRESETS.products()], header: 'large' },
  { id: 'detail', label: 'Fiche détail', icon: 'tag', blocks: () => [BLOCK_PRESETS.detail()], header: 'transparent' },
  { id: 'panier', label: 'Panier', icon: 'shopping-cart', blocks: () => [BLOCK_PRESETS.cart()], header: 'large' },
  { id: 'paiement', label: 'Paiement Mobile Money', icon: 'wallet', blocks: () => [BLOCK_PRESETS.checkout()], header: 'compact' },
  { id: 'confirmation', label: 'Confirmation', icon: 'circle-check', blocks: () => [BLOCK_PRESETS.success()], header: 'none' },
  { id: 'reservation', label: 'Réservation', icon: 'calendar-days', blocks: () => [BLOCK_PRESETS.booking()], header: 'compact' },
  { id: 'suivi', label: 'Suivi en direct', icon: 'route', blocks: () => [BLOCK_PRESETS.tracking()], header: 'transparent' },
  { id: 'profil', label: 'Profil', icon: 'user', blocks: () => [BLOCK_PRESETS.profile(), BLOCK_PRESETS.settings()], header: 'large' },
  { id: 'messages', label: 'Messagerie', icon: 'message-circle', blocks: () => [BLOCK_PRESETS.chat()], header: 'compact' },
  { id: 'formulaire', label: 'Formulaire', icon: 'clipboard-list', blocks: () => [BLOCK_PRESETS.form()], header: 'compact' },
  { id: 'offres', label: 'Abonnements', icon: 'crown', blocks: () => [BLOCK_PRESETS.plans()], header: 'compact' },
  { id: 'onboarding', label: 'Onboarding', icon: 'rocket', blocks: () => [BLOCK_PRESETS.onboarding()], header: 'none' },
  { id: 'connexion', label: 'Connexion', icon: 'lock', blocks: () => [BLOCK_PRESETS.auth()], header: 'none' },
  { id: 'tableau', label: 'Tableau de bord', icon: 'chart-line', blocks: () => [BLOCK_PRESETS.balance(), BLOCK_PRESETS.stats(), BLOCK_PRESETS.chart()], header: 'greeting' },
];

// Libellés français des propriétés (inspecteur)
export const PROP_LABELS = {
  title: 'Titre', subtitle: 'Sous-titre', eyebrow: 'Surtitre', badge: 'Badge', text: 'Texte', description: 'Description', label: 'Libellé', placeholder: 'Texte indicatif',
  items: 'Éléments', buttons: 'Boutons', media: 'Média', image: 'Image', images: 'Images', avatar: 'Photo', icon: 'Icône', action: 'Action au clic', price: 'Prix (FCFA)', oldPrice: 'Ancien prix',
  rating: 'Note', reviews: 'Nombre d\'avis', height: 'Hauteur', overlay: 'Voile', align: 'Alignement', style: 'Style', tone: 'Ton', layout: 'Disposition', columns: 'Colonnes', size: 'Taille',
  code: 'Code promo', cta: 'Bouton', meta: 'Info', value: 'Valeur', amount: 'Montant', options: 'Options', values: 'Valeurs', name: 'Nom', features: 'Points forts', quantity: 'Sélecteur de quantité',
  fee: 'Frais', feeLabel: 'Libellé des frais', ctaLabel: 'Texte du bouton', checkoutAction: 'Écran de paiement', successAction: 'Écran de confirmation', methods: 'Moyens de paiement', merchant: 'Nom du commerce',
  slots: 'Créneaux', staff: 'Équipe', service: 'Prestation', days: 'Jours affichés', unavailable: 'Créneaux pris', eta: 'Délai', status: 'Statut', courier: 'Livreur', steps: 'Étapes', to: 'Adresse', from: 'Départ',
  pins: 'Repères', route: 'Itinéraire', caption: 'Légende', date: 'Date', time: 'Heure', place: 'Lieu', seat: 'Place', holder: 'Titulaire', qr: 'QR code', hours: 'Heures', seconds: 'Durée (s)',
  phone: 'Téléphone', whatsapp: 'WhatsApp', address: 'Adresse', email: 'E-mail', trend: 'Tendance', number: 'Numéro de carte', series: 'Données', labels: 'Étiquettes', change: 'Évolution', period: 'Période',
  chartType: 'Type de graphique', max: 'Objectif', unit: 'Unité', fields: 'Champs', submit: 'Bouton d\'envoi', method: 'Méthode', social: 'Connexion Google/Apple', terms: 'Mentions', stats: 'Statistiques',
  groups: 'Groupes', toggle: 'Interrupteur', danger: 'Rouge (danger)', contact: 'Contact', messages: 'Messages', replies: 'Réponses automatiques', quick: 'Réponses rapides', slides: 'Diapositives', skip: 'Bouton « Passer »',
  illustration: 'Illustration', duration: 'Durée', line: 'Trait', q: 'Question', a: 'Réponse', author: 'Auteur', likes: 'J\'aime', comments: 'Commentaires', tag: 'Étiquette', period_: 'Période', highlight: 'Mise en avant',
  chips: 'Pastilles', number: 'Numéro', tilt: 'Bandeau incliné', speed: 'Vitesse', span: 'Largeur (colonnes)', tall: 'Tuile haute', kind: 'Type', suffix: 'Suffixe',
  vendor: 'Vendeur', filter: 'Bouton filtres', selected: 'Sélection', cart: 'Bouton panier', confetti: 'Confettis', details: 'Détails', secondary: 'Bouton secondaire', role: 'Rôle', fromItem: 'Afficher l\'élément touché',
};

// Valeurs possibles de certaines propriétés
export const ENUMS = {
  height: ['full', 'tall', 'medium', 'short'],
  overlay: ['dark', 'brand', 'light', 'none'],
  align: ['left', 'center', 'bottom'],
  tone: ['gradient', 'primary', 'accent', 'dark', 'light', 'info', 'success', 'warning', 'brand'],
  layout: ['masonry', 'grid', 'strip', 'list'],
  size: ['sm', 'md', 'lg', 'xl'],
  chartType: ['area', 'bar', 'line'],
  method: ['phone', 'email'],
  illustration: ['delivery', 'payment', 'booking', 'shopping', 'success', 'health', 'learning', 'growth', 'chat', 'location', 'gift', 'security', 'empty'],
  kind: ['image', 'video'],
};
export const STYLE_ENUMS = {
  carousel: ['card', 'wide', 'poster', 'circle', 'compact'],
  list: ['inset', 'card', 'plain'],
  categories: ['icon', 'image'],
  button: ['primary', 'secondary', 'outline', 'ghost'],
  video: ['card', 'full', 'reel'],
  progress: ['ring', 'bar'],
  balance: ['card', 'plain'],
  showcase: ['tall', 'square'],
  marquee: ['solid', 'outline'],
};
// Valeurs dépendant du bloc (même nom de propriété, sens différent)
export const BLOCK_ENUMS = {
  editorial: { tone: ['plain', 'surface', 'dark'], size: ['md', 'lg', 'xl'], align: ['left', 'center'] },
  marquee: { tone: ['primary', 'dark', 'accent', 'plain'], size: ['sm', 'md'] },
  bento: { kind: ['image', 'stat', 'text', 'feature'] },
};
export const FIELD_TYPES = ['text', 'phone', 'email', 'select', 'textarea', 'date', 'number', 'password'];
