// Généré : icônes Lucide autorisées (import nominatif = bundle léger)
import {
  Home,
  Search,
  ShoppingBag,
  ShoppingCart,
  Heart,
  User,
  Users,
  Bell,
  Settings,
  Menu,
  X,
  Check,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownLeft,
  Plus,
  Minus,
  Star,
  MapPin,
  Map,
  Navigation,
  Clock,
  Calendar,
  CalendarDays,
  Phone,
  MessageCircle,
  Send,
  Mail,
  Lock,
  ShieldCheck,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
  PiggyBank,
  Receipt,
  TrendingUp,
  TrendingDown,
  ChartBar,
  ChartLine,
  PieChart,
  Activity,
  Zap,
  Flame,
  Sparkles,
  Gift,
  Tag,
  Percent,
  Truck,
  Bike,
  Car,
  CarTaxiFront,
  Bus,
  Plane,
  Package,
  PackageCheck,
  Store,
  Utensils,
  ChefHat,
  Pizza,
  Coffee,
  CupSoda,
  Soup,
  Sandwich,
  Salad,
  Drumstick,
  Croissant,
  IceCream,
  Cake,
  Apple,
  Carrot,
  Fish,
  Scissors,
  Brush,
  Palette,
  Shirt,
  Gem,
  Crown,
  Dumbbell,
  HeartPulse,
  Stethoscope,
  Pill,
  Hospital,
  Syringe,
  Baby,
  GraduationCap,
  BookOpen,
  School,
  Lightbulb,
  Brain,
  Music,
  Headphones,
  Film,
  Video,
  Camera,
  Image,
  Mic,
  Play,
  Pause,
  Smartphone,
  Laptop,
  Globe,
  Leaf,
  Sprout,
  Sun,
  CloudSun,
  CloudRain,
  Droplets,
  Wind,
  Thermometer,
  Tractor,
  Wheat,
  Building,
  Building2,
  Hotel,
  Bed,
  Bath,
  Key,
  Sofa,
  Wrench,
  Hammer,
  Paintbrush,
  SprayCan,
  Ticket,
  PartyPopper,
  Trophy,
  Medal,
  Target,
  Flag,
  Filter,
  SlidersHorizontal,
  LayoutGrid,
  List,
  Share2,
  Download,
  Upload,
  Copy,
  Pencil,
  Trash2,
  Eye,
  LogOut,
  Info,
  CircleAlert,
  CircleHelp,
  QrCode,
  ScanLine,
  Fingerprint,
  Smile,
  ThumbsUp,
  Bookmark,
  Repeat,
  RefreshCw,
  Timer,
  Hourglass,
  Award,
  BadgeCheck,
  Handshake,
  Briefcase,
  Newspaper,
  Megaphone,
  Rocket,
  Locate,
  Route,
  Warehouse,
  Boxes,
  Recycle,
  Moon,
  Languages,
  Dog,
  Cat,
  Flower2,
  TreePine,
  Mountain,
  Waves,
  Umbrella,
  Tent,
  Ship,
  TrainFront,
  Fuel,
  CircleDollarSign,
  HandCoins,
  Landmark,
  Scale,
  FileText,
  ClipboardList,
  ClipboardCheck,
  Calculator,
  MapPinned,
  Luggage,
  Headset,
  Tv,
  Gamepad2,
  Puzzle,
  WandSparkles,
  Glasses,
  Watch,
  Footprints,
  ShoppingBasket,
  IdCard,
  Shield,
  Wifi,
  SunMedium,
  Box,
  House,
  HandHeart,
  CircleCheck,
  CirclePlay,
  Layers,
  Book,
  NotebookPen,
} from 'lucide-react';

export const ICON_MAP = {
  'home': Home,
  'search': Search,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'heart': Heart,
  'user': User,
  'users': Users,
  'bell': Bell,
  'settings': Settings,
  'menu': Menu,
  'x': X,
  'check': Check,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-left': ArrowDownLeft,
  'plus': Plus,
  'minus': Minus,
  'star': Star,
  'map-pin': MapPin,
  'map': Map,
  'navigation': Navigation,
  'clock': Clock,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'phone': Phone,
  'message-circle': MessageCircle,
  'send': Send,
  'mail': Mail,
  'lock': Lock,
  'shield-check': ShieldCheck,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'banknote': Banknote,
  'coins': Coins,
  'piggy-bank': PiggyBank,
  'receipt': Receipt,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'pie-chart': PieChart,
  'activity': Activity,
  'zap': Zap,
  'flame': Flame,
  'sparkles': Sparkles,
  'gift': Gift,
  'tag': Tag,
  'percent': Percent,
  'truck': Truck,
  'bike': Bike,
  'car': Car,
  'car-taxi-front': CarTaxiFront,
  'bus': Bus,
  'plane': Plane,
  'package': Package,
  'package-check': PackageCheck,
  'store': Store,
  'utensils': Utensils,
  'chef-hat': ChefHat,
  'pizza': Pizza,
  'coffee': Coffee,
  'cup-soda': CupSoda,
  'soup': Soup,
  'sandwich': Sandwich,
  'salad': Salad,
  'drumstick': Drumstick,
  'croissant': Croissant,
  'ice-cream': IceCream,
  'cake': Cake,
  'apple': Apple,
  'carrot': Carrot,
  'fish': Fish,
  'scissors': Scissors,
  'brush': Brush,
  'palette': Palette,
  'shirt': Shirt,
  'gem': Gem,
  'crown': Crown,
  'dumbbell': Dumbbell,
  'heart-pulse': HeartPulse,
  'stethoscope': Stethoscope,
  'pill': Pill,
  'hospital': Hospital,
  'syringe': Syringe,
  'baby': Baby,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  'school': School,
  'lightbulb': Lightbulb,
  'brain': Brain,
  'music': Music,
  'headphones': Headphones,
  'film': Film,
  'video': Video,
  'camera': Camera,
  'image': Image,
  'mic': Mic,
  'play': Play,
  'pause': Pause,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'globe': Globe,
  'leaf': Leaf,
  'sprout': Sprout,
  'sun': Sun,
  'cloud-sun': CloudSun,
  'cloud-rain': CloudRain,
  'droplets': Droplets,
  'wind': Wind,
  'thermometer': Thermometer,
  'tractor': Tractor,
  'wheat': Wheat,
  'building': Building,
  'building-2': Building2,
  'hotel': Hotel,
  'bed': Bed,
  'bath': Bath,
  'key': Key,
  'sofa': Sofa,
  'wrench': Wrench,
  'hammer': Hammer,
  'paintbrush': Paintbrush,
  'spray-can': SprayCan,
  'ticket': Ticket,
  'party-popper': PartyPopper,
  'trophy': Trophy,
  'medal': Medal,
  'target': Target,
  'flag': Flag,
  'filter': Filter,
  'sliders-horizontal': SlidersHorizontal,
  'layout-grid': LayoutGrid,
  'list': List,
  'share-2': Share2,
  'download': Download,
  'upload': Upload,
  'copy': Copy,
  'pencil': Pencil,
  'trash-2': Trash2,
  'eye': Eye,
  'log-out': LogOut,
  'info': Info,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  'qr-code': QrCode,
  'scan-line': ScanLine,
  'fingerprint': Fingerprint,
  'smile': Smile,
  'thumbs-up': ThumbsUp,
  'bookmark': Bookmark,
  'repeat': Repeat,
  'refresh-cw': RefreshCw,
  'timer': Timer,
  'hourglass': Hourglass,
  'award': Award,
  'badge-check': BadgeCheck,
  'handshake': Handshake,
  'briefcase': Briefcase,
  'newspaper': Newspaper,
  'megaphone': Megaphone,
  'rocket': Rocket,
  'locate': Locate,
  'route': Route,
  'warehouse': Warehouse,
  'boxes': Boxes,
  'recycle': Recycle,
  'moon': Moon,
  'languages': Languages,
  'dog': Dog,
  'cat': Cat,
  'flower-2': Flower2,
  'tree-pine': TreePine,
  'mountain': Mountain,
  'waves': Waves,
  'umbrella': Umbrella,
  'tent': Tent,
  'ship': Ship,
  'train-front': TrainFront,
  'fuel': Fuel,
  'circle-dollar-sign': CircleDollarSign,
  'hand-coins': HandCoins,
  'landmark': Landmark,
  'scale': Scale,
  'file-text': FileText,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'calculator': Calculator,
  'map-pinned': MapPinned,
  'luggage': Luggage,
  'headset': Headset,
  'tv': Tv,
  'gamepad-2': Gamepad2,
  'puzzle': Puzzle,
  'wand-sparkles': WandSparkles,
  'glasses': Glasses,
  'watch': Watch,
  'footprints': Footprints,
  'shopping-basket': ShoppingBasket,
  'id-card': IdCard,
  'shield': Shield,
  'wifi': Wifi,
  'sun-medium': SunMedium,
  'box': Box,
  'house': House,
  'hand-heart': HandHeart,
  'circle-check': CircleCheck,
  'circle-play': CirclePlay,
  'layers': Layers,
  'book': Book,
  'notebook-pen': NotebookPen,
};
